In [1]:
# Numpy

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
# Creating arrays(1D)

In [5]:
sample_array = np.array([1,2,3,4])

In [6]:
sample_array

array([1, 2, 3, 4])

In [7]:
# 2D Array(Matrix)

In [8]:
sample_array2 = np.array([[1,2],[3,4]])

In [9]:
sample_array2

array([[1, 2],
       [3, 4]])

In [10]:
# 3D Array(Tensor)

In [11]:
sample_array3 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

In [12]:
sample_array3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
# Dimensions
# 0 - D(Scalar) - Number
# 1 - D(Vector) - List
# 2 - D(Matrix) - A table with rows and columns
# 3 - D(Tensor) - A stack of tables

In [14]:
sample_array = np.array([
    [[91,92],[93,94]],
    [[95,96],[97,98]]
])

In [15]:
sample_array

array([[[91, 92],
        [93, 94]],

       [[95, 96],
        [97, 98]]])

In [16]:
# Array Properties

In [17]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [18]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# Shape

In [20]:
sample_array.shape

(2, 3)

In [21]:
sample_array.ndim

2

In [22]:
sample_array.size

6

In [23]:
sample_array.dtype

dtype('int64')

In [24]:
sample_array2 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

In [25]:
sample_array2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
sample_array2.shape

(2, 2, 3)

In [27]:
sample_array2.ndim

3

In [28]:
sample_array2.size

12

In [29]:
sample_array2.dtype

dtype('int64')

In [30]:
sample_array = np.array([[0,0,0],[0,0,0]])

In [31]:
sample_array

array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
sample_array2 = np.array([[1,1,1],[1,1,1]])

In [33]:
sample_array2

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
# Special arrays

In [35]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [38]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
# 1 D

In [40]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [41]:
a

array([1, 2, 3])

In [42]:
b

array([4, 5, 6])

In [43]:
a + b

array([5, 7, 9])

In [44]:
a - b

array([-3, -3, -3])

In [45]:
a * b

array([ 4, 10, 18])

In [46]:
a / b

array([0.25, 0.4 , 0.5 ])

In [47]:
# Mathematical functions

In [48]:
sample_array= np.array([1,4,9])

In [49]:
sample_array

array([1, 4, 9])

In [50]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [51]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [52]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [53]:
# Statistical functions

In [54]:
sample_array = np.array([1,2,3,4,5,6,7,8,9])

In [55]:
sample_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.mean(sample_array)

np.float64(5.0)

In [57]:
np.median(sample_array)

np.float64(5.0)

In [58]:
np.std(sample_array)

np.float64(2.581988897471611)

In [59]:
np.min(sample_array)

np.int64(1)

In [60]:
np.max(sample_array)

np.int64(9)

In [61]:
sample_array = np.array([68,67,58,1003])

In [62]:
sample_array

array([  68,   67,   58, 1003])

In [63]:
np.mean(sample_array)

np.float64(299.0)

In [64]:
np.median(sample_array)

np.float64(67.5)

In [65]:
np.std(sample_array)

np.float64(406.47324635208156)

In [66]:
np.min(sample_array)

np.int64(58)

In [67]:
np.max(sample_array)

np.int64(1003)

In [68]:
# Flattening

In [69]:
sample_array = np.array([[1,2],[3,4]])

In [70]:
sample_array

array([[1, 2],
       [3, 4]])

In [71]:
sample_array.flatten()

array([1, 2, 3, 4])

In [72]:
sample_array = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

In [73]:
sample_array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [74]:
sample_array.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
a = np.array([1,2])
b = np.array([3,4])

In [76]:
a

array([1, 2])

In [77]:
b

array([3, 4])

In [78]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [79]:
sample_array = np.array([1,2,3,4])

In [80]:
sample_array

array([1, 2, 3, 4])

In [81]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [82]:
# Random Module

In [83]:
np.random.rand(3)

array([0.47094978, 0.61553154, 0.36290254])

In [84]:
np.random.rand(10)

array([0.74802313, 0.66540147, 0.31524667, 0.14553834, 0.55229478,
       0.8535662 , 0.92082371, 0.48897031, 0.65356466, 0.87671055])

In [85]:
np.random.randint(1,100,10)

array([24, 76, 49, 30, 91, 13, 96, 12, 65, 18], dtype=int32)

In [86]:
sample_array = np.array([[1,2],[3,4]])

In [87]:
sample_array

array([[1, 2],
       [3, 4]])

In [88]:
np.sum(sample_array,axis = 0)

array([4, 6])

In [89]:
np.sum(sample_array,axis=1)

array([3, 7])

In [90]:
sample_array = np.array([[1,np.nan,3]])

In [91]:
sample_array

array([[ 1., nan,  3.]])

In [92]:
np.isnan(sample_array)

array([[False,  True, False]])

In [93]:
sample_array2 = np.array([[1,np.nan],[np.nan,4]])

In [94]:
sample_array2

array([[ 1., nan],
       [nan,  4.]])

In [95]:
np.isnan(sample_array2)

array([[False,  True],
       [ True, False]])

In [96]:
sample_array = np.arange(6)

In [97]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [98]:
reshaped = sample_array.reshape(2,3)

In [99]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [100]:
sample_array.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])